name: Build and Push Multi-Arch Image to Aliyun ACR

on:
  push:
    branches: [ "main", "master" ]
    # 可选：仅当 Dockerfile 或本 workflow 文件变更时才触发
    paths:
      - '/bitnami-postgresql/Dockerfile'
      - '.github/workflows/build-and-push-to-acr.yml'
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  # 阿里云 ACR 配置（通过 GitHub Secrets 注入）
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}        # 例如: registry.cn-hangzhou.aliyuncs.com
  ACR_NAMESPACE: ${{ secrets.ACR_NAMESPACE }}      # 命名空间
  IMAGE_NAME: bitnami-postgresql                   # 镜像名称

jobs:
  build-and-push-multi-arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./bitnami-postgresql
          file: ./bitnami-postgresql/Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          sbom: false
          push: true
          tags: |
            ${{ env.ACR_REGISTRY }}/${{env.ACR_NAMESPACE}}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_REGISTRY }}/${{env.ACR_NAMESPACE}}/${{ env.IMAGE_NAME }}:${{ github.sha }}